UI/COMB.SpaParking.MVC/Controllers/ParkingAreaController.cs
using COMB.SpaParking.Application.ParkingAreas;
using COMB.SpaParking.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace COMB.SpaParking.MVC.Controllers
{
    [Authorize(Roles = Roles.CustomerServiceRep)]
    public class ParkingAreaController : BaseController
    {
        readonly Infrastructure.ICOMBParkingApi _api;
        readonly ILogger<ParkingAreaController> _logger;

        public ParkingAreaController(ILogger<ParkingAreaController> logger, Infrastructure.ICOMBParkingApi api)
        {
            _api = api;
            _logger = logger;
        }

        List<SelectListItem> ToAspDropdownDataSource(Models.ParkingAreasFilterModel model, 
            IReadOnlyCollection<IParkingAreaType> parkingAreaTypes)
        {
            var listItems= new List<SelectListItem>
            {
                new SelectListItem("Show All Status", "0", true),
            };
            parkingAreaTypes.ToList()
                .ForEach(x => listItems.Add(new SelectListItem(x.ParkingAreaTypeDescription, x.Id.ToString(), x.Id == model.ParkingAreaTypeId)));
            return listItems;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery]Models.ParkingAreasFilterModel model)
        {
            if (!ModelState.IsValid)
                return BadRequestResult();

            ViewBag.CurrentFilter = model;
            var readingParkingAreaTypes = _api.ReadParkingAreaTypesAsync();
            await readingParkingAreaTypes;
            readingParkingAreaTypes.Result.Do(lst => ViewBag.ParkingAreaTypes = ToAspDropdownDataSource(model, lst));
            var response = await _api.ReadParkingAreasAsync(ParkingAreaFilterFactory.Create(model));
            return response.Match<IActionResult>(
                ok => { 
                    return View(ok);
                },
                ko => { 
                    return View(new List<IParkingArea>());
                });
        }
        
    }
}

UI/COMB.SpaParking.MVC/Controllers/ParkingPermitController.cs
using COMB.SpaParking.Application.ParkingPermits;
using COMB.SpaParking.MVC.Infrastructure;
using COMB.SpaParking.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace COMB.SpaParking.MVC.Controllers
{
    [Authorize(Roles = Roles.CustomerServiceRep)]
    public class ParkingPermitController : BaseController
    {
        readonly ILogger<ParkingPermitController> _logger;
        readonly ICOMBParkingApi _api;
        public ParkingPermitController(ICOMBParkingApi api, ILogger<ParkingPermitController> logger)
        {
            _api = api;
            _logger = logger;
        }

        List<SelectListItem> ToAspDropdownDataSource(Models.ParkingPermitsFilterModel model)
        {
            return new List<SelectListItem>
            {
                new SelectListItem("Show All Status", "", model.Expired is null),
                new SelectListItem("Expired", "true", model.Expired == true),
                new SelectListItem("Active", "false", model.Expired == false)
            };
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] Models.ParkingPermitsFilterModel model)
        {
            if (!ModelState.IsValid)
                return BadRequestResult();

            ViewBag.CurrentFilter = model;
            ViewBag.ExpiredDropdownDataSource = ToAspDropdownDataSource(model);
            var response = await _api.ReadParkingPermitsAsync(ParkingPermitFilterFactory.Create(model));
            return response.Match<IActionResult>(
                ok => {
                    return View(ok);
                },
                ko => {
                    return View(new List<IParkingPermit>());
                });
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var response = await _api.GetParkingPermitAsync(id);
            return response.Match<IActionResult>(
                ok =>
                {
                    return View(ok);
                },
                ko =>
                {
                    return NotFound();
                });
        }

        [HttpGet]
        public IActionResult ConfirmDeactivate(int id)
        {
            if (id == 0)
                return BadRequestResult();
            return View(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Deactivate([FromForm]DeactivateParkingPermitModel model)
        {
            if (!ModelState.IsValid)
                return BadRequestResult();

            var response = await _api.DeactivateParkingPermitAsync(model.Id);
            return response.Match<IActionResult>(
                ok =>
                {
                    return RedirectToAction("Index");
                },
                ko =>
                {
                    return NotFound();
                });
        }

    }
}

UI/COMB.SpaParking.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Parkings - City of Miami Beach</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/COMB.SpaParking.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Parkings - City of Miami Beach</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (User.Identity.IsAuthenticated) 
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ParkingArea" asp-action="Index">Parking Areas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ParkingPermit" asp-action="Index">Parking Permits</a>
                            </li>
                        </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>